snowflake_account = "WKIUQHU-SB67362"
snowflake_user = "SHIKHERJAIN"
snowflake_password = "Sh!kherj@!n786"
snowflake_role = "ACCOUNTADMIN"
snowflake_warehouse = "COMPUTE_WH"
snowflake_database = "INSPECTION_DB"
snowflake_schema = "PUBLIC"